Descriptive statistics
samuelgoodall/NLPProjekt pull request #29
Opened 2023-03-20 08:32 UTC by jana370

2023-03-23 09:55 UTC, samuelgoodall requested changes

2023-03-23 09:55 UTC, samuelgoodall commented on qualitative_information_extractor.py
>          #sentence = re.sub(r"(?<!\\)\$.*?(?<!\\)\$", "", sentence)
remove dead code dont just comment it out

2023-03-23 09:55 UTC, samuelgoodall commented on qualitative_information_extractor.py
> +    def clean_sentence_from_none_ASCII(self, sentence: str):
add documentation for this method explain what it does

2023-03-23 09:55 UTC, samuelgoodall commented on descriptiveStatistic.py
Very nice job i like how you commented the different sections of the visualisation :D

2023-03-23 09:55 UTC, samuelgoodall commented on cutOffDataset.py
> +    def chunk_list(self, lst, chunk_size):
nice use of generators! its a clean and good solution! 
can you tell me why you used generators vs splitting the list manually?

2023-03-23 09:55 UTC, samuelgoodall commented on cutOffDataset.py
its very nice that you commented all the methods! 
The code looks clean and is readable good job!
We might want to talk with Dennis for testing purposes because there are lots of moving parts that can go wrong

2023-03-23 09:59 UTC, samuelgoodall commented
If possible pls move the descriptive statistics in its own folder

2023-03-27 06:47 UTC, jana370 commented on qualitative_information_extractor.py
>          #sentence = re.sub(r"(?<!\\)\$.*?(?<!\\)\$", "", sentence)
done

2023-03-27 06:50 UTC, jana370 commented on qualitative_information_extractor.py
> +    def clean_sentence_from_none_ASCII(self, sentence: str):
like this
only for this one?

2023-03-27 15:14 UTC, samuelgoodall approved these changes

2023-03-29 14:33 UTC, merged