Embedding sbert class
samuelgoodall/NLPProjekt pull request #30
Opened 2023-03-21 14:11 UTC by elliegarcia

Created a wrapper class for the SBERT embeddings. Please especially look over the hyperparameters in the SentenceTransformerEmbedding class

2023-03-23 08:40 UTC, samuelgoodall requested changes
Looks good just minor changes for documentation style

2023-03-23 08:40 UTC, samuelgoodall commented on experiments/embedding_methods/sbert_embedding.py
> +    def return_hyper_params(self):
add docstrings documentation: 
https://numpydoc.readthedocs.io/en/latest/format.html
https://realpython.com/documenting-python-code/#docstring-formats

2023-03-23 08:40 UTC, samuelgoodall commented on experiments/embedding_methods/sbert_embedding.py
> +        """
Use Numpy docstring style:
https://numpydoc.readthedocs.io/en/latest/format.html
example is in the glove embedding class

2023-03-23 10:55 UTC, samuelgoodall commented on experiments/embedding_methods/sbert_embedding.py
> +        """
make sure the model that we use is getting the correct input-> does it have to be uncased?

2023-03-23 12:39 UTC, samuelgoodall commented on experiments/embedding_methods/sbert_embedding.py
> +        """
well have to make sure we dont cutoff long sentences like ansgar mentioned in the meeting

2023-03-25 16:21 UTC, elliegarcia commented on experiments/embedding_methods/sbert_embedding.py
> +    def return_hyper_params(self):
I added more notation to the sbert wrapper class, could you look over it?

2023-03-25 16:30 UTC, elliegarcia commented on experiments/embedding_methods/sbert_embedding.py
> +        """
As I understand the uncased model strips the casing of the words, I think we don't need to feed it uncased sentences.
Added the 512 cutoff.

2023-03-29 14:30 UTC, merged